packages:
  - 'apps/*'
  - 'packages/*'
  - 'playground'

allowBuilds:
  '@ffmpeg-installer/linux-x64': true
  esbuild: true
allowUnusedPatches: true
patchedDependencies:
  mpegts.js@1.8.0: patches/mpegts.js@1.8.0.patch
